#ifndef RESOURCESSERVER_GLOBAL_H
#define RESOURCESSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RESOURCESSERVER_LIBRARY)
#  define RESOURCESSERVER_EXPORT Q_DECL_EXPORT
#else
#  define RESOURCESSERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // RESOURCESSERVER_GLOBAL_H
